### ISSUE TITLE
add setup.py /packaging

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/vautomator-serverless#48]
This allow users to install the program. The ondemand.py file should be added a binary to install in setup.py as well.

That way, one can install the package and just call `ondemand.py` (or, may I suggest, rename it "vaautomator-ondemand" or similar as well) without having to swap to a custom virtual env, or doing anything special

**Comment by caggle** [comment]
This makes a lot of sense.

Also, I should probably separate the requirements for the examples/clients, the actual serverless app, and tests.

**Comment by caggle** [comment]
I decided to move the client specific stuff to its own repository: https://github.com/mozilla/vautomator-client and will keep track of client related issues in there.

Closing this issue and will open a new one in the above repo.
